### ISSUE TITLE
Create separate functions for Versioning and Deploy to allow for more flexibility

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-version-controller#10]
As a user of the NodeJSPipeline, I need the ability to influence the deploy stage without impacting any versioning operations.

**Comment by AHumanFromCA** [comment]
This should be done by splitting out the versioning and deploy operations into 2 separate functions. This would allow one to be changed while keeping the other as default. I can pick this up real quick after getting zowe/zowe-cli#142 completed.

**Comment by zFernand0** [comment]
An alternative implementation is to just add the version functions without affecting the the deploy.
This will constitute a feature enhancement instead of an immediate breaking change to the shared libraries. Later on the deploy functions can be cleaned up (i.e. remove version bump, hence causing a major breaking change)

**Comment by zFernand0** [comment]
Duplication of code has been avoided in the v1.x line after adding the `versioning` function
