### ISSUE TITLE
Fix transient failures in nightly Deploy All pipeline

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli-version-controller#134]
Normally they may seem innocent enough, but they happen frequently and can bite us. For example, last night a new version of @zowe/zos-console-for-zowe-sdk@next failed to deploy, which caused installation of @zowe/cli@next to fail.

**Comment by t1m0thyj** [comment]
A few days ago, I updated the Deploy Component pipeline configuration to save 100 build logs instead of just 20 in the Jenkins GUI, but forgot that running the pipeline resets this back to 20. After updating the Groovy script so that it stops doing this (https://github.com/zowe/zowe-cli-version-controller/commit/8b705a7a91f1f6453851b87248a7287040b6873b), we should hopefully be able to obtain more error details. 🙂

**Comment by zFernand0** [comment]
Closing as we have moved the Zowe Deploy All to GHA and to another repo 
- See: https://github.com/zowe/zowe-cli-standalone-package/actions
