### ISSUE TITLE
Build step causes undesired behaviors when other tgz files are sourced

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-version-controller#9]
Based on the logic, if someone were to have a tgz file sourced in the root of their project, the following two things will occur.
1. The `npm pack` file, along with all other sourced tgz files, will get archived by the build.
    - Since the given name will be something like `my-package-1.0.0.tgz the-sourced.tgz`
2. The sourced tgz files get removed by the build step
    - This could cause undesired behavior in the case where people depend on them for integration testing purposes.
    - Command: `rm -f my-package-1.0.0.tgz the-sourced.tgz`

https://github.com/zowe/zowe-cli-version-controller/blob/f883a9134b8d7979137987916c5bc41ed1508ba4/src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy#L150-L157

**Comment by AHumanFromCA** [comment]
Do you have a way to change the name of the file that gets built? Or should we say that if they depend on the tgz file in their integration phase, they should ignore the file and unarchive it in the necessary step, that way it doesn't make it into the commit tree.

I would lean towards ignoring the file and unarchiving it as needed. I am not sure if it is a good practice to source build artifacts but the capability to unarchive this file does exist.

**Comment by AHumanFromCA** [comment]
Also pretty sure if there are 2 tgz files, this command will fail entirely so that would need addressed

**Comment by AHumanFromCA** [comment]
Would you say this holds up zowe/zowe-cli#142?

**Comment by zFernand0** [comment]
> Also pretty sure if there are 2 tgz files, this command will fail entirely so that would need addressed

http://ant.apache.org/manual/Types/fileset.html

**Comment by AHumanFromCA** [comment]
> > Also pretty sure if there are 2 tgz files, this command will fail entirely so that would need addressed

> http://ant.apache.org/manual/Types/fileset.html

Care to explain?

**Comment by zFernand0** [comment]
> Do you have a way to change the name of the file that gets built? Or should we say that if they depend on the tgz file in their integration phase, they should ignore the file and unarchive it in the necessary step, that way it doesn't make it into the commit tree.
> 
> I would lean towards ignoring the file and unarchiving it as needed. I am not sure if it is a good practice to source build artifacts but the capability to unarchive this file does exist.

There is something that could be done here. 
1. Grab the output of the `npm pack` command (and save it in a variable)
2. Tail the output of that command (and you are guaranteed that the tgz file name is there)
    ![image](https://user-images.githubusercontent.com/37381190/52570309-1386be80-2de1-11e9-97f8-6b7c634ab708.png)

**Comment by zFernand0** [comment]
> > > Also pretty sure if there are 2 tgz files, this command will fail entirely so that would need addressed
> 
> > http://ant.apache.org/manual/Types/fileset.html
> 
> Care to explain?

Based on the JEnkins documentaion as to how the [ArchiveArtifacts command](https://jenkins.io/doc/pipeline/steps/core/#archiveartifacts-archive-the-artifacts) works, you can see that the `artifacts` string follows the [`includes` attribute of the Ant fileset](http://ant.apache.org/manual/Types/fileset.html)

**Comment by AHumanFromCA** [comment]
How's this?

https://github.com/zowe/zowe-cli-version-controller/blob/680d438de48b75c9e06032e5c4604ad2cc0e8348/src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy#L150-L165

**Comment by zFernand0** [comment]
I agree with having the revision string as part of the artifact.
Also, thanks for using the package name provided by the `npm pack` command. That solves the issue.
Now it's up to NPM's behavior here, i.e. if there is already a `scope-my-package-1.0.0.tgz` it will be overwritten by NPM.
Closing the issue.
