### ISSUE TITLE
Show NPM vulnerabilities as separate status item in GitHub

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-cli-version-controller#96]
It is possible for a Jenkins pipeline to send multiple statuses through the GitHub webhook. For example, Zowe Explorer already does this:
![image](https://user-images.githubusercontent.com/50887074/81097669-36196180-8ed6-11ea-95ac-d4eb8ee46041.png)

When NPM vulnerabilities are found, it would be nice if they showed as a separate GitHub status. The way they are shown now (as part of the `pr-merge` build), it is unclear whether the build failed because of a lint/test error or because of a vulnerability.

**Comment by t1m0thyj** [comment]
Closing this as it has been implemented as a separate status item in GH Actions 🙂
